config/routes.rb
NearSpeak::Application.routes.draw do
  # api v1
  namespace :api, :defaults => { :format => :json }  do
    namespace :v1 do
      post 'login/get_auth_token'
      post 'login/getAuthToken', to: 'login#get_auth_token'
      post 'login/sign_out'
      post 'login/signOut', to: 'login#sign_out'
      post 'login/sign_in_with_facebook'
      post 'login/signInWithFacebook', to: 'login#sign_in_with_facebook'

      get 'tags/show'
      get 'tags/show_by_hardware_id'
      get 'tags/showByHardwareId', to: 'tags#show_by_hardware_id'
      get 'tags/showMyTags', to: 'tags#show_my_tags'
      get 'tags/supported_language_codes'
      get 'tags/supportedLanguageCodes', to: 'tags#supported_language_codes'
      get 'tags/supportedBeaconUUIDs', to: 'tags#get_all_uuids'
      post 'tags/create'
      post 'tags/add_hardware_id_to_tag'
      post 'tags/addHardwareIdToTag', to: 'tags#add_hardware_id_to_tag'
    end
  end

  root :to => 'overview#index'

  devise_for :customers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :customers, :except => [:index]

  resources :places

  resources :tags

  resources :text_records, :except => [:index]

  resources :translations, :except => [:index]

  resources :name_translations, :except => [:index]

  resources :hardwares, :except => [:index]
end

app/controllers/overview_controller.rb
##
# The overview controller.
class OverviewController < ApplicationController
  before_action :authenticate_customer!

  ##
  # Show the overview (dashboard) view.
  def index
    if current_customer.role == 'admin'
      @tags = Tag.all
      @places = Place.all
      @top10_tags = Tag.top_10_scanned
    else
      @tags = Tag.my(current_customer)
      @places = Place.my(current_customer)
      @top10_tags = Tag.my_top_10_scanned(current_customer)
    end
  end
end

app/views/overview/_places.html.erb
<%- model_class = Place -%>

<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <%= link_to(places_path) do %>
        <div class="title">
          <i class="fa fa-map-marker"></i>
          <%=  model_class.model_name.human(:count => 2).titleize %>
          <% unless @places.nil? %>
              (<%= @places.count %>)
          <% end %>
        </div>
    <% end %>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
      </tr>
      </thead>
      <tbody>
      <% unless @places.nil? %>
          <% @places.each do |place| %>
              <tr>
                <td><%= link_to place.name, place_path(place) %></td>
                <td><%= place.description %></td>
              </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/overview/_tags.html.erb
<%- model_class = Tag -%>

<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <%= link_to(tags_path) do %>
        <div class="title">
          <i class="fa fa-comment"></i>
          <%= model_class.model_name.human(:count => 2).titleize %>
          <% unless @tags.nil? %>
            (<%= @tags.count %>)
          <% end %>
        </div>
    <% end %>
  </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
      </tr>
      </thead>
      <tbody>
      <% unless @tags.nil? %>
          <% @tags.each do |tag| %>
            <% if tag.hardwares.length < 1 %>
                  <tr>
                    <td><%= link_to tag.display_name, tag_path(tag), :class => 'text-contrast' %></td>
                    <td><%= link_to l(tag.created_at, format: :short), tag_path(tag), :class => 'text-contrast' %></td>
                  </tr>
            <% else %>
                  <tr>
                    <td><%= link_to tag.display_name, tag_path(tag) %></td>
                    <td><%= link_to l(tag.created_at, format: :short), tag_path(tag) %></td>
                  </tr>
            <% end %>
          <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/overview/_tags_top10.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-bar-chart"></i>
      <%= t('overview_top10_scanned_tags') %>
    </div>
  </div>
  <div class="panel-body">
    <%= column_chart (Tag.my_top10_chart_data(current_customer)), colors: ["#f5f5f5"], stacked: true %>
  </div>
</div>

app/views/overview/index.html.erb
<%= render partial: 'layouts/navbar', :locals => { :title => 'Dashboard', :icon => 'fa fa-tachometer', :levelOne => nil, :levelTwo => nil, :levelThree => nil } %>

<div class="row">
  <div class="col-md-12">
    <div class="well well-sm">
      
      <%= render :partial => 'tags_top10' %>
      
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="well well-sm">

      <%= render :partial => 'tags' %>

    </div>
  </div>
  <div class="col-md-6">
    <div class="well well-sm">

      <%= render :partial => 'places' %>

    </div>
  </div>
</div>