config/routes.rb
NearSpeak::Application.routes.draw do
  # api v1
  namespace :api, :defaults => { :format => :json }  do
    namespace :v1 do
      post 'login/get_auth_token'
      post 'login/getAuthToken', to: 'login#get_auth_token'
      post 'login/sign_out'
      post 'login/signOut', to: 'login#sign_out'
      post 'login/sign_in_with_facebook'
      post 'login/signInWithFacebook', to: 'login#sign_in_with_facebook'

      get 'tags/show'
      get 'tags/show_by_hardware_id'
      get 'tags/showByHardwareId', to: 'tags#show_by_hardware_id'
      get 'tags/showMyTags', to: 'tags#show_my_tags'
      get 'tags/supported_language_codes'
      get 'tags/supportedLanguageCodes', to: 'tags#supported_language_codes'
      get 'tags/supportedBeaconUUIDs', to: 'tags#get_all_uuids'
      post 'tags/create'
      post 'tags/add_hardware_id_to_tag'
      post 'tags/addHardwareIdToTag', to: 'tags#add_hardware_id_to_tag'
    end
  end

  root :to => 'overview#index'

  devise_for :customers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :customers, :except => [:index]

  resources :places

  resources :tags

  resources :text_records, :except => [:index]

  resources :translations, :except => [:index]

  resources :name_translations, :except => [:index]

  resources :hardwares, :except => [:index]
end

app/controllers/api/v1/tags_controller.rb
##
# The API tag controller.
class API::V1::TagsController < API::V1::ApiApplicationController
  
  ##
  # Get infos about a specific tag via the nearspeak ID.
  #
  # @return [String] The requested tag as JSON object.
  def show
    tag_identifier = params[:id]
    lang_code = params[:lang]

    tag = Tag.with_tag_identifier(tag_identifier).active.first
    
    unless tag.nil?
      # check if the tag is currently active
      unless tag.currently_active
        tag = nil
      end
    
      tag_scanned(tag)
    end

    return_tag_infos(tag, lang_code)
  end

  ##
  # Get infos about a specific tag via the hardware identifier.
  #
  # @return [String] The requested tag as JSON object.
  def show_by_hardware_id
    hardware_id = params[:id]
    hardware_type = params[:type]

    # optional
    lang_code = params[:lang]
    latitude = params[:lat]
    longitude = params[:lon]
    ble_major = params[:major]
    ble_minor = params[:minor]

    error = []
    if hardware_id.nil?
      error << 'id'
    end

    if hardware_type.nil?
      error << 'type'
    end

    # also require major und minor id by bluetooth beacons
    unless hardware_type.nil?
      if hardware_type == HardwaresHelper::TYPE_BLE
        if ble_major.nil?
          error << 'major'
        end

        if ble_minor.nil?
          error << 'minor'
        end
      end
    end

    if error.length > 0
      return_error_infos(400, 'Request values are missing', 'InvalidRequest', error)
      return
    end

    if hardware_type == HardwaresHelper::TYPE_BLE
      tag = Tag.show_by_ble_hardware_id(hardware_id, hardware_type, ble_major, ble_minor)
    else
      tag = Tag.show_by_hardware_id(hardware_id, hardware_type)
    end

    # add location to hardware
    unless latitude.nil? and longitude.nil? and tag.nil?
      tag.add_location_to_hardware(hardware_id, latitude, longitude)
    end

    # update scan counter
    unless tag.nil?
      tag_scanned(tag)
    end

    return_tag_infos(tag, lang_code)
  end

  ##
  # Show all tags from the current customer.
  #
  # @return [String] The requested tag as JSON object.
  def show_my_tags
    tags = Tag.where('customer_id = ? AND active = ?', current_customer.id, true)

    if tags.nil?
      return_error_infos(400, 'No tags found', 'NoTagsFound', nil)
    else
      json_tags = []

      tags.each { |tag| json_tags << create_tag_infos(tag, nil) }

      render :status => 200, :json => { :tags => json_tags }
    end
  end

  ##
  # Create a new nearspeak tag in the system.
  def create
    text = params[:text]
    lang_code = params[:lang]
    purchase_id = params[:purchase_id]

    # optional
    gender = params[:gender]
    auth_token =  params[:auth_token]
    hardware_id = params[:hardware_id]
    hardware_type = params[:hardware_type]
    name = params[:name]
    parent_id = params[:parent_id]
    latitude = params[:lat]
    longitude = params[:lon]
    ble_major = params[:major]
    ble_minor = params[:minor]

    customer = nil

    error = []
    if text.nil?
      error << 'text'
    end

    if lang_code.nil?
      error << 'lang'
    end

    if purchase_id.nil?
      error << 'purchase_id'
    end

    # also require major und minor id by bluetooth beacons
    unless hardware_type.nil?
      if hardware_type == HardwaresHelper::TYPE_BLE
        if ble_major.nil?
          error << 'major'
        end

        if ble_minor.nil?
          error << 'minor'
        end
      end
    end

    if  error.length > 0
      return_error_infos(400, 'Request values are missing', 'InvalidRequest', error)
      return
    end

    unless TranslationsHelper.is_valid_language(lang_code)
      return_error_infos(400, 'Wrong language code', 'WrongLanguageCode', nil)
      return
    end

    unless auth_token.nil?
      customer_token = params[:auth_token].presence
      customer = customer_token && Customer.find_by_auth_token(customer_token)

      if customer && Devise.secure_compare(customer.get_devise_auth_token, customer_token)
        sign_in customer, store: false
      end
    end

    status, tag, error_msg, error_code = Tag.create_with_data(text, lang_code, purchase_id, gender, hardware_id, hardware_type, ble_major, ble_minor, name, parent_id, latitude, longitude, customer)

    if status.nil?
      return_error_infos(400, 'Error while creating new tag', 'CreationError', nil)
    else
      if status != 200
        return_error_infos(status, error_msg, error_code, nil)
      else
        if lang_code.nil?
          return_tag_infos(tag, nil)
        else
          return_tag_infos(tag, lang_code)
        end
      end
    end
  end

  ##
  # Add a hardware to a nearspeak tag.
  def add_hardware_id_to_tag
    tag = Tag.find_by_tag_identifier(params[:id])
    hardware_id = params[:hardware_id]
    hardware_type = params[:hardware_type]

    #optional
    latitude = params[:lat]
    longitude = params[:lon]
    ble_major = params[:major]
    ble_minor = params[:minor]

    if  hardware_id.nil?
      return_error_infos(400, 'Hardware ID is missing', 'HardwareIDMissing', nil)
      return
    end

    error = []

    if hardware_type.nil?
      error << 'hardware_type'
    end

    # also require major und minor id by bluetooth beacons
    unless hardware_type.nil?
      if hardware_type == HardwaresHelper::TYPE_BLE
        if ble_major.nil?
          error << 'major'
        end

        if ble_minor.nil?
          error << 'minor'
        end
      end
    end

    if  error.length > 0
      return_error_infos(400, 'Request values are missing', 'InvalidRequest', error)
      return
    end

    if tag.nil?
      return_error_infos(400, 'Tag not found', 'TagNotFound', nil)
    else
      status, tag, error_msg, error_code = tag.add_hardware_id_to_tag(hardware_id, hardware_type, ble_major, ble_minor, latitude, longitude)

      if status.nil?
        return_error_infos(400, 'Error while updating tag', 'InvalidRequest', nil)
      else

        if status != 200
          return_error_infos(status, error_msg, error_code, nil)
        else
          return_tag_infos(tag, nil)
        end
      end
    end
  end

  ##
  # Get all supported translation languages by bing back.
  def supported_language_codes
    language_codes = TranslationsHelper.supported_language_codes

    if language_codes.empty?
      return_error_infos(400, 'Error no supported languages', 'TranslationError', nil)
    else
      render :status => 200, :json => { :language_codes => language_codes }
    end
  end
  
  ##
  # Get all supported iBeacon UUIDs from the server.
  def get_all_uuids
    ble_uuids = Hardware.all_ble_uuids.map { |hw| hw.identifier }
    
    render :status => 200, :json => { :uuids => ble_uuids }
  end

  ### PRIVATE ###
  private

  ##
  # Creates json hash for linked tags.
  def create_linked_tag_infos(tag, language_code)
    return_tag = {}

    unless tag.nil?
      return_tag[:id] = tag.id
      return_tag[:tag_identifier] = tag.tag_identifier

      if language_code.nil? and !tag.original_name.nil?
        return_tag[:name] = tag.original_name.text.to_s
        return_tag[:lang] = tag.original_name.lang_code.to_s
      elsif !language_code.nil?
        return_tag[:name] = tag.get_name_translation(language_code)
        return_tag[:lang] = language_code
      end
    end

    return_tag
  end

  ##
  # Creates json hash for a tag.
  def create_tag_infos(tag, language_code)
    return_tag = {}

    # tag infos
    unless tag.nil?
      return_tag[:id] = tag.id
      return_tag[:tag_identifier] = tag.tag_identifier

      unless tag.description.nil? or tag.description.empty?
        return_tag[:description] = tag.description
      end

      unless tag.place.nil?
        return_tag[:places] = tag.place.id
      end

      # name
      # show original name if no lang_code is set
      if language_code.nil? and !tag.original_name.nil?
        return_tag[:name] = { :text => tag.original_name.text, :lang => tag.original_name.lang_code }
      elsif !language_code.nil? and tag.name_translations.count > 0
        return_tag[:name] = { :text => tag.get_name_translation(language_code), :lang => language_code }
      end

      # text_record infos
      unless tag.text_record.nil?
        unless tag.text_record.gender.nil?
          return_tag[:gender] = tag.text_record.gender
        end

        unless tag.text_record.image_url.empty?
          return_tag[:image_url] = tag.text_record.image_url
        end

        unless tag.text_record.text_url.empty?
          return_tag[:text_url] = tag.text_record.text_url
        end

        # show original text if no lang_code is set
        if language_code.nil? and !tag.text_record.original_text.nil?
          text = tag.text_record.original_text.text.to_s
          lang_code = tag.text_record.original_text.lang_code.to_s
        elsif !language_code.nil? and tag.text_record.translations.count > 0
          text = tag.text_record.get_translation(language_code)
          lang_code = language_code

          # convert to string
          text = text.to_s
        end

        unless text.nil?
          unless text.empty?
            return_tag[:translation] = { :text => text, :lang => lang_code }
          end
        end
      end

      # linked tags
      if tag.has_children?
        linked_tags = []
        tag.children.all.each { |t| linked_tags << create_linked_tag_infos(t, language_code) }
        return_tag[:linked_tags] = linked_tags
      end

      # parent tag
      unless tag.is_root?
        return_tag[:parent_tag] = create_linked_tag_infos(tag.parent, language_code)
      end

      # hardware
      unless tag.hardwares.nil? or tag.hardwares.count < 1
        hw_items = []
        tag.hardwares.each do |item|
          hw = {}

          hw[:type] = item.hardware_type
          hw[:identifier] = item.identifier

          if location = item.current_location
            hw[:latitude] = location.latitude
            hw[:longitude] = location.longitude

app/controllers/tags_controller.rb
##
# The tags controller.
class TagsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /Tags
  # GET /Tags.json
  def index
    if current_customer.role == 'admin'
      @tags = Tag.all
    else
      @tags = Tag.my(current_customer)
    end
  end

  # GET /Tags/1
  # GET /Tags/1.json
  def show
    unless @tag.nil?
      @text_record = @tag.text_record

      unless @text_record.nil?
        @translations = @text_record.translations
      end

      @name_translations = @tag.name_translations

      if @tag.hardwares.count > 0
        @hardwares = @tag.hardwares

        # generate google map location
        @showMap = false
        
        @markers = []
        
        @tag.hardwares.with_location().each do | hardware |
          unless hardware.current_location.nil?
            @showMap = true

            @markers << { :lat => hardware.current_location.latitude, :lng => hardware.current_location.longitude }
          end
        end
        
      end
    end
  end

  # GET /Tags/new
  def new
    @tag = Tag.new
    if params[:mode] == 'in_mode'
      @tag.place_id = params['place_id']
    end

    @tag_limit_reached = true
    
    if Tag.my(current_customer).count <= MAX_TAG_PER_CUSTOMER
      @tag_limit_reached = false
    end
  end

  # GET /Tags/1/edit
  def edit
  end

  # POST /Tags
  # POST /Tags.json
  def create
    @tag = Tag.new(tag_params)
    @tag.customer = current_customer

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tag }
      else
        format.html { render action: 'new' }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Tags/1
  # PATCH/PUT /Tags/1.json
  def update
    unless @tag.nil?
      respond_to do |format|
        if @tag.update(tag_params)
          format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @tag.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /Tags/1
  # DELETE /Tags/1.json
  def destroy
    unless @tag.nil?
      @tag.destroy
      respond_to do |format|
        format.html { redirect_to tags_url }
        format.json { head :no_content }
      end
    end
  end

  ### PRIVATE ###
  private
  
  ##
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    if current_customer.role == 'admin'
      @tag = Tag.find(params[:id])
    else
      @tag = Tag.where('id = ? AND customer_id = ?', params[:id], current_customer).first
    end
  end

  ##
  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:place_id, :name, :description, :tag_identifier, :original_name, :parent_id, :active, :active_start_time, :active_stop_time, :active_time, :active_date, :active_start_date, :active_stop_date)
  end
end

app/views/tags/_form.html.erb
<%= simple_form_for @tag, :html => { :class => 'form-horizontal' } do |f| %>
    
<div class="panel panel-default">    
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-pencil"></i>
      <%=t 'tag_details' %>
    </div>
  </div>

  <div class="panel-body">
    <%= f.input :place_id, :as => :hidden %>
    <%= f.input :description, :input_html => { :class => 'form-control' } %>
    <%= f.input :parent_id, label_method: :display_name, value_method: :id, collection: Tag.where(:customer_id => current_customer.id), prompt: t('tag_select_partent_tag'), :input_html => { :class => 'form-control' } %>
  
    <% if Place.where(:customer_id => current_customer.id).count > 0 %>
    <%= f.association :place, collection: Place.where(:customer_id => current_customer.id), prompt: t('tag_select_place'), :input_html => { :class => 'form-control' } %>
    <% end %>
    <div class="checkbox">
    <%= f.label :active do %>
      <%= f.check_box :active %>
      <%= t('tag_is_active') %>
    <% end %>
    </div>
  </div>
</div>

<hr class="hr-normal">

<div class="panel panel-default">    
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-sun-o"></i>
      <%=t 'tag_active_time' %>
    </div>
  </div>

  <div class="panel-body">
    <div class="checkbox">
    <%= f.label :active_time do %>
      <%= f.check_box :active_time %>
      <%= t('tag_is_active_time_enabled') %>
    <% end %>
    </div>
    <hr class="hr-normal">
    <div class="timepicker input-group" id="timepicker">
    <%= f.input :active_start_time, as: :string, label: false, placeholder: t('tag_active_time_start'), :input_html => { :class => 'form-control' , 'data-format' => "hh:mm" } %>

    <span class="input-group-addon">
    <span data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-time"></span>
    </span>
    </div>
    <div class="timepicker input-group" id="timepicker">
    <%= f.input :active_stop_time, as: :string, label: false, placeholder: t('tag_active_time_stop'), :input_html => { :class => 'form-control' , 'data-format' => "hh:mm" } %>

    <span class="input-group-addon">
    <span data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-time"></span>
    </span>
    </div>
  </div>
</div>

<hr class="hr-normal">

<div class="panel panel-default">    
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-eye"></i>
      <%=t 'tag_active_date' %>
    </div>
  </div>

  <div class="panel-body">
    <div class="checkbox">
    <%= f.label :active_date do %>
      <%= f.check_box :active_date %>
      <%= t('tag_is_active_date_enabled') %>
    <% end %>
    </div>
    <hr class="hr-normal">
    
    <div class="input-group">
      <input class="form-control daterange" placeholder="<%= t('tag_active_date_daterange') %>" value="<%= @tag.active_date_to_string %>" type="text">
      <span class="input-group-addon" id="daterange">
        <i class="icon-calendar"></i>
      </span>
    </div>
    
    <script>
    $("#daterange").daterangepicker({
      format: "MM.DD.YYYY"
    }, function(start, end) {
      var dateFormat = "DD.MM.YYYY"
      $("#tag_active_start_date").val(start.format(dateFormat));
      $("#tag_active_stop_date").val(end.format(dateFormat));
      return $("#daterange").parent().find("input").first().val(start.format(dateFormat) + " - " + end.format(dateFormat));
    });
    </script>
    
    <%= f.input :active_start_date, :as => :hidden %>
    <%= f.input :active_stop_date, :as => :hidden %>
  </div>
</div>
      
<div class="form-actions">
  <%= f.button :submit, :class => 'btn btn-primary' %>

  <% if @tag.id.nil? %>

  <%= link_to t('helpers.links.cancel', :default => t('helpers.links.cancel')), tags_path(), :class => 'btn btn-default' %>

  <% else %>

  <%= link_to t('helpers.links.cancel', :default => t('helpers.links.cancel')), tag_path(), :class => 'btn btn-default' %>

  <% end %>
</div>
<% end %>

app/views/tags/_hardware_tableview.html.erb
<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-hdd-o"></i>
      <%= Hardware.model_name.human(:count => 2).titleize %>
    </div>
  </div>
  <div class="panel-body">
    <% unless hardwares.nil? %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= Hardware.human_attribute_name(:identifier) %></th>
          <th><%= Hardware.human_attribute_name(:hardware_type) %></th>
          <th><%= Hardware.human_attribute_name(:location) %></th>
          <th><%= Hardware.human_attribute_name(:major) %></th>
          <th><%= Hardware.human_attribute_name(:minor) %></th>
          <th><%= t 'helpers.actions', :default => t('helpers.actions') %></th>
        </tr>
      </thead>
      <tbody>

        <% hardwares.each do |hardware| %>
        <tr>
          <td><%= hardware.identifier %></td>
          <td><%= hardware.hardware_type %></td>
          <% if hardware.current_location.nil? %>
          <td>&nbsp;</td>
          <% else %>
          <td><%= hardware.current_location.latitude %> | <%= hardware.current_location.longitude %></td>
          <% end %>
          <% if hardware.major.nil? %>
          <td>&nbsp;</td>
          <% else %>
          <td><%= hardware.major %></td>
          <% end %>
          <% if hardware.minor.nil? %>
          <td>&nbsp;</td>
          <% else %>
          <td><%= hardware.minor %></td>
          <% end %>
          <td>
            <%= link_to(edit_hardware_path(hardware, :tag_id => tag.id), :class => 'btn btn-default') do %>
            <i class="fa fa-pencil"></i>
            <% end %>

            <%= link_to(hardware_path(hardware, :tag_id => tag.id),
            :method => :delete,
            :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
            :class => 'btn btn-danger') do %>
              <i class="fa fa-trash-o"></i>

              <% end %>
            </td>
          </tr>
          <% end %>

        </tbody>
      </table>
      <% end %>

      <% unless tag.nil? %>
      <div class="form-actions">
        <%= link_to t('helpers.titles.new', model: Hardware.model_name.human.titleize, :default => t('helpers.titles.new')),
        new_hardware_path(:mode => 'in_mode', :tag_id => tag.id),
        :class => 'btn btn-default' %>
      </div>
      <% end %>

    </div>
    <% unless hardwares.nil? %>
    <% unless @markers.nil? or @showMap == false %>
      
    <div class="panel panel-default panel-body">
      <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
      <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
    
      <style>
      #map {
        margin-top: 20px;
        height: 300px;
      }
      </style>
    
      <div id="map"></div>
    
      <script type="text/javascript">
      var map = L.map('map').setView([0, 0], 17);

      // add an OpenStreetMap tile layer
      L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);
        
      var markers = []
      
      <% @markers.each do |location| %>
      var marker = new L.marker([<%= location[:lat] %>, <%= location[:lng] %>]).addTo(map);

      markers.push(marker)

      <% end %>

      var group = new L.featureGroup(markers);

      map.fitBounds(group.getBounds());
      </script>
    </div>
      
    <% end %>
    <% end %>
  </div>

app/views/tags/_names_tableview.html.erb
<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-bullhorn"></i>
      <%= NameTranslation.model_name.human(:count => 2).titleize %>
    </div>
  </div>
  <div class="panel-body">
    <% unless name_translations.nil? %>
        <table class="table table-striped">
          <thead>
          <tr>
            <th><%= NameTranslation.human_attribute_name(:lang_code) %></th>
            <th><%= NameTranslation.human_attribute_name(:text) %></th>
            <th><%=t 'helpers.actions' %></th>
          </tr>
          </thead>
          <tbody>

          <% name_translations.each do |name_translation| %>
              <tr>
                <td><%= name_translation.lang_code %></td>
                <td><%= name_translation.text %></td>
                <td>
                  <%= link_to(edit_name_translation_path(name_translation, :tag_id => tag.id), :class => 'btn btn-default') do %>
                      <i class="fa fa-pencil"></i>
                  <% end %>
                  <% if name_translation.original_name_id.nil? %>
                      <%= link_to(name_translation_path(name_translation, :tag_id => tag.id),
                                  :method => :delete,
                                  :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
                                  :class => 'btn btn-danger') do %>
                          <i class="fa fa-trash-o"></i>
                      <% end %>
                  <% end %>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>
    <% end %>

    <% unless @tag.nil? %>
        <div class="form-actions">
          <%= link_to t('helpers.titles.new', model: NameTranslation.model_name.human.titleize, :default => t('helpers.titles.new')),
                      new_name_translation_path(:mode => 'in_mode', :tag_id => tag.id),
                      :class => 'btn btn-default' %>
        </div>
    <% end %>
  </div>
</div>

app/views/tags/_tag_limit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-pencil"></i>
      <%=t 'tag' %>
    </div>
  </div>
  <div class="panel-body">
    <div class="panel panel-default panel-body">
      <p>You have reached the <b>maximum tags limit</b>, please contact us. <%= mail_to 'support@nearspeak.at'%></p>
    </div>
  </div>
</div>

app/views/tags/_translations_tableview.html.erb
<div class="panel panel-default" style="margin-bottom:10px;">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-flag"></i>
      <%= Translation.model_name.human(:count => 2).titleize %>
    </div>
  </div>
  <div class="panel-body">
    <% unless translations.nil? %>
        <table class="table table-striped">
          <thead>
          <tr>
            <th><%= Translation.human_attribute_name(:lang_code) %></th>
            <th><%= Translation.human_attribute_name(:text) %></th>
            <th><%= t 'helpers.actions', :default => t('helpers.actions') %></th>
          </tr>
          </thead>
          <tbody>

          <% translations.each do |translation| %>
              <tr>
                <td><%= translation.lang_code %></td>
                <td><%= translation.text %></td>
                <td>

                  <%= link_to(edit_translation_path(translation, :tag_id => tag.id), :class => 'btn btn-default') do %>
                      <i class="fa fa-pencil"></i>
                  <% end %>

                  <% if translation.original_text_id.nil? %>

                      <%= link_to(translation_path(translation, :tag_id => tag.id),
                                  :method => :delete,
                                  :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
                                  :class => 'btn btn-danger') do %>
                          <i class="fa fa-trash-o"></i>
                      <% end %>

                  <% end %>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>
    <% end %>

    <% unless tag.nil? %>
        <div class="form-actions">
          <%= link_to t('helpers.titles.new', model: Translation.model_name.human.titleize, :default => t('helpers.titles.new')),
                      new_translation_path(:mode => 'in_mode', :tag_id => tag.id),
                      :class => 'btn btn-default' %>
        </div>
    <% end %>
  </div>
</div>

app/views/tags/edit.html.erb
<%- model_class = Tag -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 1).titleize, :icon => 'fa fa-comment', :levelOne => model_class.model_name.human(:count => 1).titleize, :levelTwo => nil, :levelThree => nil } %>

<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<%- model_class = Tag -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 2).titleize, :icon => 'fa fa-comment', :levelOne => model_class.model_name.human(:count => 2).titleize, :levelTwo => nil, :levelThree => nil } %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t 'helpers.actions', :default => t('helpers.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @tags.each do |tag| %>
      <tr>
      <% if tag.hardwares.length < 1 %>
            <td><%= link_to tag.display_name, tag_path(tag), :class => 'text-contrast' %></td>
      <% else %>
            <td><%= link_to tag.display_name, tag_path(tag) %></td>
      <% end %>
        <td><%= l(tag.created_at, format: :short) %></td>
        <td>
          
          <%= link_to(edit_tag_path(tag), :class => 'btn btn-default') do %>
              <i class="fa fa-pencil"></i>
          <% end %>

          <%= link_to(tag_path(tag),
                      :method => :delete,
                      :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
                      :class => 'btn btn-danger') do %>
              <i class="fa fa-trash-o"></i>
          <% end %>

      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('helpers.titles.new', model: model_class.model_name.human.titleize , :default => t('helpers.titles.new')),
              new_tag_path(:mode => 'in_mode'),
              :class => 'btn btn-primary' %>
</div>

app/views/tags/new.html.erb
<%- model_class = Tag -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 1).titleize, :icon => 'fa fa-comment', :levelOne => model_class.model_name.human(:count => 1).titleize, :levelTwo => nil, :levelThree => nil } %>

<% if @tag_limit_reached %>
<%= render :partial => 'tag_limit' %>
<% else %>
<%= render :partial => 'form' %>
<% end %>