config/routes.rb
NearSpeak::Application.routes.draw do
  # api v1
  namespace :api, :defaults => { :format => :json }  do
    namespace :v1 do
      post 'login/get_auth_token'
      post 'login/getAuthToken', to: 'login#get_auth_token'
      post 'login/sign_out'
      post 'login/signOut', to: 'login#sign_out'
      post 'login/sign_in_with_facebook'
      post 'login/signInWithFacebook', to: 'login#sign_in_with_facebook'

      get 'tags/show'
      get 'tags/show_by_hardware_id'
      get 'tags/showByHardwareId', to: 'tags#show_by_hardware_id'
      get 'tags/showMyTags', to: 'tags#show_my_tags'
      get 'tags/supported_language_codes'
      get 'tags/supportedLanguageCodes', to: 'tags#supported_language_codes'
      get 'tags/supportedBeaconUUIDs', to: 'tags#get_all_uuids'
      post 'tags/create'
      post 'tags/add_hardware_id_to_tag'
      post 'tags/addHardwareIdToTag', to: 'tags#add_hardware_id_to_tag'
    end
  end

  root :to => 'overview#index'

  devise_for :customers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :customers, :except => [:index]

  resources :places

  resources :tags

  resources :text_records, :except => [:index]

  resources :translations, :except => [:index]

  resources :name_translations, :except => [:index]

  resources :hardwares, :except => [:index]
end

app/models/place.rb
##
# The Place model can combine multiple nearspeak tags into one location.
class Place < ActiveRecord::Base
  validates :latitude, presence: true
  validates :longitude, presence: true
  
  belongs_to :customer
  has_many :tags
  
  scope :my, ->(current_customer) { where("customer_id = ?", current_customer).order(id: :desc) }
end

app/controllers/places_controller.rb
##
# The places controller.
class PlacesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    if current_customer.role == 'admin'
      @places = Place.all
    else
      @places = Place.my(current_customer)
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @tags = @place.tags
  end

  # GET /places/new
  def new
    @place = Place.new
    
    # default location: Mopius HQ
    set_default_location
  end

  # GET /places/1/edit
  def edit
    if @place.latitude.nil? or @place.longitude.nil?
      set_default_location
    end
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.customer = current_customer

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        if @place.latitude.nil? or @place.longitude.nil?
          set_default_location
        end
        
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  ### PRIVATE ###
  private
  
  ##
  # Use callbacks to share common setup or constraints between actions.
  def set_place
    if current_customer.role == 'admin'
      @place = Place.find(params[:id])
    else
      @place = Place.where('id = ? AND customer_id = ?', params[:id], current_customer).first
    end
  end

  ##
  # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:name, :description, :image, :latitude, :longitude)
  end
  
  ##
  # Sthe the default location, to the Mopius HQ.
  def set_default_location
    @place.latitude = 48.168739
    @place.longitude = 16.333480
  end
end

app/views/places/_form.html.erb
<%= simple_form_for @place, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="panel panel-default panel-body">

    <%= f.input :name, :input_html => { :class => 'form-control' } %>
    <%= f.input :description, :input_html => { :class => 'form-control' } %>
    <%= f.input :latitude, :input_html => { :class => 'form-control' } %>
    <%= f.input :longitude, :input_html => { :class => 'form-control' } %> 
        
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
    
    <style>
      #map {
        margin-top: 20px;
        height: 300px;
      }
    </style>
    
    <div id="map"></div>
    
    <script type="text/javascript">
    var map = L.map('map').setView([<%= @place.latitude %>, <%= @place.longitude %>], 17);

    // add an OpenStreetMap tile layer
    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var startLat = <%= @place.latitude %>;
    var startLon = <%= @place.longitude %>;

    document.getElementById("place_latitude").value = startLat;
    document.getElementById("place_longitude").value = startLon;

    var marker = L.marker([startLat, startLon], { draggable: 'true' }).addTo(map);
    marker.on('dragend', function(event) {
      var marker = event.target;
      var position = marker.getLatLng();
      marker.setLatLng(new L.LatLng(position.lat, position.lng), { draggable: 'true' });
      map.panTo(new L.LatLng(position.lat, position.lng))
  
      document.getElementById("place_latitude").value = position.lat;
      document.getElementById("place_longitude").value = position.lng;
    });
    </script>
    
    <hr class="hr-normal">
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn btn-primary' %>

      <% if @place.id.nil? %>
          <%= link_to t('helpers.links.cancel', :default => t('helpers.links.cancel')),
                      places_path(), :class => 'btn btn-default' %>
      <% else %>
          <%= link_to t('helpers.links.cancel', :default => t('helpers.links.cancel')),
                      place_path(), :class => 'btn btn-default' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/places/_tags_tableview.html.erb
<% unless tags.nil? %>
    <% if tags.count > 0 %>
        <div class="panel panel-default" style="margin-bottom:10px;">
          <div class="panel panel-heading">
            <div class="title">
              <i class="fa fa-comment"></i>
              <%= Tag.model_name.human(:count => 2).titleize %>
            </div>
          </div>
          <div class="panel panel-default panel-body">
            <table class="table table-striped">
              <thead>
              <tr>
                <th><%= Tag.human_attribute_name(:name) %></th>
                <th><%= Tag.human_attribute_name(:description) %></th>
                <th><%=t 'helpers.actions', :default => t('helpers.actions') %></th>
              </tr>
              </thead>
              <tbody>

              <% tags.each do |tag| %>
                  <tr>
                    <% unless tag.original_name.nil? %>
                        <td><%= tag.original_name.text %></td>
                    <% end %>
                    <td><%= tag.description %></td>
                    <td>
                      <%= link_to(edit_tag_path(tag, :tag_id => tag.id), :class => 'btn btn-default') do %>
                          <i class="fa fa-pencil"></i>
                      <% end %>

                    </td>
                  </tr>
              <% end %>

              </tbody>
            </table>
          </div>
        </div>
    <% end %>
<% end %>

app/views/places/edit.html.erb
<%- model_class = Place -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 1).titleize, :icon => 'fa fa-map-marker', :levelOne => model_class.model_name.human(:count => 1).titleize, :levelTwo => nil, :levelThree => nil } %>

<%= render :partial => 'form' %>

app/views/places/index.html.erb
<%- model_class = Place -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 2).titleize, :icon => 'fa fa-map-marker', :levelOne => model_class.model_name.human(:count => 2).titleize, :levelTwo => nil, :levelThree => nil } %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t 'helpers.actions', :default => t('helpers.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <% @places.each do |place| %>
      <tr>
        <td><%= link_to place.name, place_path(place) %></td>
        <td><%= place.description %></td>
        <td><%= l(place.created_at, format: :short) %></td>
        <td>
          <%= link_to(edit_place_path(place), :class => 'btn btn-default') do %>
              <i class="fa fa-pencil"></i>
          <% end %>

          <%= link_to(place_path(place),
                      :method => :delete,
                      :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
                      :class => 'btn btn-danger') do %>
              <i class="fa fa-trash-o"></i>
          <% end %>

        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('helpers.titles.new', model: model_class.model_name.human.titleize , :default => t('helpers.titles.new')),
              new_place_path(:mode => 'in_mode'),
              :class => 'btn btn-primary' %>
</div>

app/views/places/new.html.erb
<%- model_class = Place -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 1).titleize, :icon => 'fa fa-map-marker', :levelOne => model_class.model_name.human(:count => 1).titleize, :levelTwo => nil, :levelThree => nil } %>

<%= render :partial => 'form' %>

app/views/places/show.html.erb
<%- model_class = Place -%>

<%= render partial: 'layouts/navbar', :locals => { :title => model_class.model_name.human(:count => 1).titleize, :icon => 'fa fa-map-marker', :levelOne => model_class.model_name.human(:count => 1).titleize, :levelTwo => nil, :levelThree => nil } %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="title">
      <i class="fa fa-pencil"></i>
      <%=t 'place_details' %>
    </div>
  </div>
  <div class="panel-body">
    <% unless @place.name.nil? %>
        <div class="panel panel-default panel-body">
          <h4 class="title text-primary"><%= @place.name %></h4>
          <small><%= model_class.human_attribute_name(:name) %></small>
        </div>
    <% end %>

    <% unless @place.description.nil? or @place.description.empty? %>
        <div class="panel panel-default panel-body">
          <h5 class="title text-primary"><%= @place.description %></h5>
          <small><%= model_class.human_attribute_name(:description) %></small>
        </div>
    <% end %>
    
    <% unless @place.latitude.nil? or @place.longitude.nil? %>
    <div class="panel panel-default panel-body">
      <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
      <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
    
      <style>
        #map {
          margin-top: 20px;
          height: 300px;
        }
      </style>
    
      <div id="map"></div>
    
      <script type="text/javascript">
      var map = L.map('map').setView([<%= @place.latitude %>, <%= @place.longitude %>], 17);

      // add an OpenStreetMap tile layer
      L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
          attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

      L.marker([<%= @place.latitude %>, <%= @place.longitude %>]).addTo(map);
      </script>
      
    </div>
    <% end %>

  </div>
</div>

<%= render partial: 'tags_tableview', :locals => { :tags => @tags } %>

<div class="form-actions">
  <%= link_to t('helpers.links.back', :default => t('helpers.links.back')),
              places_path, :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.edit', :default => t('helpers.links.edit')),
              edit_place_path(@place), :class => 'btn btn-default' %>
  <%= link_to t('helpers.links.destroy', :default => t('helpers.links.destroy')),
              place_path(@place),
              :method => 'delete',
              :data => { :confirm => t('helpers.links.confirm', :default => t('helpers.links.confirm', :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>