config/routes.rb
NearSpeak::Application.routes.draw do
  # api v1
  namespace :api, :defaults => { :format => :json }  do
    namespace :v1 do
      post 'login/get_auth_token'
      post 'login/getAuthToken', to: 'login#get_auth_token'
      post 'login/sign_out'
      post 'login/signOut', to: 'login#sign_out'
      post 'login/sign_in_with_facebook'
      post 'login/signInWithFacebook', to: 'login#sign_in_with_facebook'

      get 'tags/show'
      get 'tags/show_by_hardware_id'
      get 'tags/showByHardwareId', to: 'tags#show_by_hardware_id'
      get 'tags/showMyTags', to: 'tags#show_my_tags'
      get 'tags/supported_language_codes'
      get 'tags/supportedLanguageCodes', to: 'tags#supported_language_codes'
      get 'tags/supportedBeaconUUIDs', to: 'tags#get_all_uuids'
      post 'tags/create'
      post 'tags/add_hardware_id_to_tag'
      post 'tags/addHardwareIdToTag', to: 'tags#add_hardware_id_to_tag'
    end
  end

  root :to => 'overview#index'

  devise_for :customers, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  resources :customers, :except => [:index]

  resources :places

  resources :tags

  resources :text_records, :except => [:index]

  resources :translations, :except => [:index]

  resources :name_translations, :except => [:index]

  resources :hardwares, :except => [:index]
end

app/views/layouts/_company_footer.erb
<div class="login-container-footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="text-center">
          <a href="mailto:office@nearspeak.at">&copy; 2015 Nearspeak</a> | <a href="https://www.nearspeak.at/terms-of-use/"><%=t :footer_terms %></a> | <a href="https://www.nearspeak.at/contact/"><%=t :footer_contact %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_mainbar.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <%= image_tag('logo.svg', size: '130x21', alt: 'Nearspeak', class: 'logo') %>
      </a>
    </div>
    
    <% if customer_signed_in? %>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to(current_customer.get_customer_name, customer_path(current_customer)) %></li>
        <li>
          <%= link_to(destroy_customer_session_path, :method => :delete) do %>
            <%=t :devise_signout %>
          <% end %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/_mainnav.erb
<ul class="nav nav-sidebar">
  <% if controller_name == 'overview' %>
      <li class="active">
  <% else %>
      <li class="">
  <% end %>

  <a href="/">
    <span>Dashboard</span>
  </a>
  </li>
  
  <% if controller_name == 'tags' %>
      <li class="active">
  <% else %>
      <li class="">
  <% end %>

  <%= link_to(tags_path) do %>
      <span><%=t  Tag.model_name.human(:count => 2).titleize %></span>
  <% end %>
  </li>
  
  <% if controller_name == 'places' %>
      <li class="active">
  <% else %>
      <li class="">
  <% end %>

  <%= link_to(places_path) do %>
      <span><%=t  Place.model_name.human(:count => 2).titleize %></span>
  <% end %>

  </li>
</ul>

app/views/layouts/_navbar.erb
<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <h1 class="pull-left">
        <% if icon.nil? %>
        <i class="fa fa-tag"></i>
        <% else %>
        <i class="<%= icon %>"></i>
        <% end %>
        <span><a href="/"><%= title %></a></span>
      </h1>
    </div>
    
    <% unless levelOne.nil? %>
    <div class="pull-right">
      <ol class="breadcrumb">
        <li>
          <a href="/">
            <i class="fa fa-bar-chart"></i>
          </a>
        </li>
        
        <li class="separator">
          <i class="fa fa-angle-right"></i>
        </li>
        <li><%= levelOne %></li>
        

        <% unless levelTwo.nil? %>
        <li class="separator">
          <i class="fa fa-angle-right"></i>
        </li>
        <li class="active"><%= levelTwo %></li>
        <% end %>

        <% unless levelThree.nil? %>
        <li class="separator">
          <i class="fa fa-angle-right"></i>
        </li>
        <li class="active"><%= levelThree %></li>
        <% end %>

      </ol>
    </div>
    <% end %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Nearspeak" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>
  <%= render '/layouts/mainbar' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render '/layouts/mainnav' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%# messages %>
        <div class='row'>
          <div class='col-sm-12'>
            <% flash.each do |name, msg| %>
                <div class="alert alert-<%= name == :notice ? 'success' : 'info' %> alert-dismissable">
                  <a class="close" data-dismiss="alert" href="#">×</a>
                  <i class="icon-info-sign"></i>
                  <%= msg if msg.is_a?(String) %>
                </div>
            <% end %>
          </div>
        </div>

        <%= yield %>
        
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Nearspeak" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>

<body>
  <div class="container">
      
    <div class="row">

      <%# messages %>
      <div class='col-sm-4 col-sm-offset-4'>

        <%= devise_error_messages! %>

        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == :notice ? 'success' : 'info' %> alert-dismissable">
              <a class="close" data-dismiss="alert" href="#">×</a>
              <i class="icon-info-sign"></i>
              <%= msg if msg.is_a?(String) %>
            </div>
        <% end %>
      </div>

      <%= yield %>

    </div>

  </div> <!-- /container -->
</body>
</html>